#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

# Check Prettier standards
npm run lint ||
(
  echo '❌Prettier Check Failed❌
    Prettier Check Failed. Run "npm run format", and try commit again.';
  false;
)

# Check ESLint Standards for staged files
npx lint-staged ||
(
  echo '👋Staged files was checked!👋
    ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
  false;
)

# Check tsconfig standards
npm run check-types ||
(
  echo '🤡Failed Type check.🤡
    Are you seriously trying to write that? Make the changes required above.'
  false;
)

# If everything passes... Now we can commit
echo '🤔... Alright... Code looks good... Trying to build now. 🤔'

npm run build ||
(
  echo '❌👷🔨 Your build failed 🔨👷❌
    Next build failed: View the errors above to see why.'
  false;
)

# If everything passes... Now we can commit
echo '✅✅✅ Ok, commit. ✅✅✅'